GET http://localhost:3001/api/users/1 HTTP/1.1

###

POST http://localhost:3003/api/users HTTP/1.1
content-type: application/json

{
    "username": "hello@me.com",
    "name": "hello"
}

###

POST http://localhost:3003/api/readinglists HTTP/1.1
content-type: application/json

{
    "blogId": 1,
    "userId": 2
}

###

PUT http://localhost:3001/api/users/user2 HTTP/1.1
content-type: application/json

{
    "username": "oops@hey.dev"
}

###

DELETE http://localhost:3001/api/users/1 HTTP/1.1
content-type: application/json